import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

export const InterLightMedium = localFont({
  src:[
    {
      path: "../../public/Font/Inter/static/Inter_18pt-Medium.ttf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-interlightMedium",
  display: "swap"
});

export const Oswald = localFont({
  src:[
    {
      path: "../../public/Font/Oswald/static/Oswald-Regular.ttf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-oswald",
  display: "swap"
});

export const InterLightLight = localFont({
  src:[
    {
      path: "../../public/Font/Inter/static/Inter_18pt-Light.ttf",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-interlightLight",
  display: "swap"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${InterLightMedium.variable} ${Oswald.variable} ${InterLightLight.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
